const employees = [
  {
    employee_id: 100,
    first_name: "Steven",
    last_name: "King",
    age: 34,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1987-06-12",
    job_id: 4,
    salary: "24000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 101,
    first_name: "Alwan",
    last_name: "Fauzi",
    age: 31,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1994-06-12",
    job_id: 5,
    salary: "34000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 102,
    first_name: "Dimas",
    last_name: "Satria",
    age: 23,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1994-06-12",
    job_id: 6,
    salary: "30000.00",
    manager_id: null,
    department_id: 5,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 103,
    first_name: "Sheila",
    last_name: "Aprilia",
    age: 37,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1994-06-12",
    job_id: 4,
    salary: "42000.00",
    manager_id: null,
    department_id: 2,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 105,
    first_name: "Wahyu",
    last_name: "Putra",
    age: 44,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1994-06-12",
    job_id: 6,
    salary: "27000.00",
    manager_id: null,
    department_id: 3,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
];

module.exports = employees;
